### PR TITLE
Add handshake blockchain support

### PR DESCRIPTION
**Pull request by pcfreak30**
Add handshake to the chains schema to support https://github.com/dappnode/DNP_DAPPMANAGER/pull/1012 and https://github.com/LumeWeb/DAppNodePackage-handshake

### CODE REVIEW

**Comment by pablomendezroyo** [comment]
@dapplion @3alpha @tropicar
Do we agree to support chain cards for this blockchain? check it out at https://handshake.org/

**Comment by Pol-Lanski** [comment]
Handshake is pretty neat. If the rest of the code that comes with it is OK, happy to accept it!

**Review by dapplion — APPROVED** [review]
LGTM! But we should merge the DAPPMANAGER PR before

**Review by tropicar — APPROVED** [review]
LGTM

**Comment by pablomendezroyo** [comment]
Not implemented in dappmanager

**Comment by pcfreak30** [comment]
Just an update given you are doing a cleanup. Lume has been in heavy development for a year, which has made integration efforts to be put on hold, and this is something I will do development on when it makes sense.

Kudos!

**Pull request closed without merging**
